
CREATE TABLE users
(
    id SERIAL PRIMARY KEY NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    gender VARCHAR(1) NOT NULL
);
ALTER TABLE users
 ADD CONSTRAINT unique_email UNIQUE (email);

CREATE TABLE images
(
  id SERIAL PRIMARY KEY NOT NULL,
  content OID NOT NULL,
  user_id INT NOT NULL
);

ALTER TABLE images
ADD CONSTRAINT fk_user
FOREIGN KEY (user_id)
REFERENCES users(id);